### 错误处理

异常:
捕获错误:try...except...finally
记录错误:logging

如果不捕获错误，自然可以让Python解释器来打印出错误堆栈，但程序也被结束了。既然我们能捕获错误，就可以把错误堆栈打印出来，然后分析错误原因，同时，让程序继续执行下去

抛出错误:raise
当方法中发生错误时，该方法会创建一个对象并将其交给运行时系统。该对象称为异常对象，包含有关错误的信息，包括错误发生时的类型和程序状态。创建异常对象并将其交给运行时系统称为抛出异常.

在方法抛出异常后，运行时系统会尝试查找要处理它的内容。处理异常的可能“某事”的集合是已被调用以获取发生错误的方法的有序方法列表。方法列表称为调用堆栈.
运行时系统在调用堆栈中搜索包含可以处理异常的代码块的方法。这段代码称为异常处理程序。搜索从发生错误的方法开始，并按照调用方法的相反顺序继续通过调用堆栈。找到适当的处理程序后，运行时系统会将异常传递给处理程序。如果抛出的异常对象的类型与处理程序可以处理的类型匹配，则认为异常处理程序是合适的。选择的异常处理程序称为捕获异常。如果运行时系统穷举搜索调用堆栈上的所有方法而没有找到适当的异常处理程序，则运行时系统（以及程序）终止。

### 单元测试
### 文档测试